---
title: "Supplemental_Probs"
author: "Yu Du"
output: pdf_document
---

G&S
30. (Page 117)
(a)
```{r}
#p=0.5
1-pbinom(3,7,0.5)
#p=0.6
1-pbinom(3,7,0.6)
#p=0.7
1-pbinom(3,7,0.7)
```

(b)
```{r}
#p=0.6
i=1
while (1-pbinom(i,2*i+1,0.6)<0.95){
  i=i+1
}
i
```
```{r}
#n=67
1-pbinom(33,67,0.6)
```

4.(Page 219)
```{r}
set.seed(2021)
u<-runif(10000,0,1)
y1<-u+2
y2<-u^3
y3<-1/(u+1)
y4<-log(u+1)
hist(y1, freq = FALSE, xlab = 'y1', density = 20)
segments(x0=2,y0=1,x1=3,y1=1,col="darkblue")
```

```{r}
hist(y2, freq = FALSE, xlab = 'y2',density=30)
curve((1/3)*((x)^(-2/3)),0,1,col="darkblue",add=TRUE)
```
```{r}
hist(y3, freq =FALSE, xlab = 'y3',density=30)
curve(1/(x^2),1/2,1,col="darkblue",add=TRUE)
```
```{r}
hist(y4, freq =FALSE, xlab = 'y3',density=30)
curve(exp(x),0,log(2),col="darkblue",add=TRUE)
```
17.(page 265)
```{r}
set.seed(2021)
mean(sample(1:6,10,replace=TRUE))
var(sample(1:6,10,replace=TRUE))
```
```{r}
mean(sample(1:6,1000,replace=TRUE))
var(sample(1:6,1000,replace=TRUE))
```


